<a href="https://colab.research.google.com/github/Habib0308/University_Final_Year_Project/blob/master/Project%20Codes/Data_Preprocessing_Chicago_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Imports**

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.preprocessing import Imputer
import calendar

ImportError: ignored

In [0]:
url="https://data.cityofchicago.org/api/views/x2n5-8w5q/rows.csv?accessType=DOWNLOAD"
df= pd.read_csv(url, encoding = "utf-8")

#**Droping NULL Values**

In [0]:
df = df.dropna(how='any',axis=0)

#**Counting Rows and Columns**

In [0]:
print("Columns", df.columns.size)
print("Rows", df.size)

Columns 17
Rows 4335646


#**COLUMNS of ORIGINAL DF**

In [0]:
print("Columns", df.columns)

Columns Index(['CASE#', 'DATE  OF OCCURRENCE', 'BLOCK', ' IUCR',
       ' PRIMARY DESCRIPTION', ' SECONDARY DESCRIPTION',
       ' LOCATION DESCRIPTION', 'ARREST', 'DOMESTIC', 'BEAT', 'WARD', 'FBI CD',
       'X COORDINATE', 'Y COORDINATE', 'LATITUDE', 'LONGITUDE', 'LOCATION'],
      dtype='object')


#**Extracting Month, Year, Weekday, Hour for more better results**

In [0]:
df["DATE  OF OCCURRENCE"] = pd.to_datetime(df["DATE  OF OCCURRENCE"], format="%m/%d/%Y %I:%M:%S %p")
#https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html
#https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior

In [0]:
#https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.DatetimeIndex.html
df['year'] = pd.DatetimeIndex(df["DATE  OF OCCURRENCE"]).year
df['month'] = pd.DatetimeIndex(df["DATE  OF OCCURRENCE"]).month
df['hour'] = pd.DatetimeIndex(df["DATE  OF OCCURRENCE"]).hour
df['weekday'] = df['DATE  OF OCCURRENCE'].dt.weekday_name
df['month'] = df['month'].apply(lambda x: calendar.month_abbr[x])
df.set_index("DATE  OF OCCURRENCE", inplace=True)
df.sort_index(inplace=True)
#df['Weekday']=pd.DatetimeIndex(df["DATE  OF OCCURRENCE"]).dayofweek
#df['day_of_week'] = df['Order Date'].dt.weekday_name
#https://stackoverflow.com/questions/30222533/create-a-day-of-week-column-in-a-pandas-dataframe-using-python

#**Deleting COLUMNS**

In [0]:
del df["WARD"]#The ward (City Council district) where the incident occurred.
del df["BEAT"]#Indicates the beat where the incident occurred. A beat is the smallest police geographic area
del df["DOMESTIC"]#Indicates whether the incident was domestic-related as defined by the Illinois Domestic Violence Act.
del df[" SECONDARY DESCRIPTION"]
del df[" LOCATION DESCRIPTION"]
del df["FBI CD"]#Indicates the crime classification as outlined in the FBI's National Incident-Based Reporting System (NIBRS)
del df["CASE#"]
del df['X COORDINATE']
del df['Y COORDINATE']
del df["LATITUDE"]
del df["LONGITUDE"]
del df["LOCATION"]

In [0]:
df.head()

BLOCK  IUCR  ... hour  weekday
DATE  OF OCCURRENCE                                   ...              
2018-12-04 05:10:00     065XX S UNIVERSITY AVE  0326  ...    5  Tuesday
2018-12-04 05:15:00  083XX S COTTAGE GROVE AVE  0810  ...    5  Tuesday
2018-12-04 05:30:00      079XX S GREENWOOD AVE  1310  ...    5  Tuesday
2018-12-04 05:50:00       010XX W GLENLAKE AVE  0890  ...    5  Tuesday
2018-12-04 06:00:00       077XX S EAST END AVE  2820  ...    6  Tuesday

[5 rows x 8 columns]

In [0]:
df.head()

BLOCK  IUCR  ... hour  weekday
DATE  OF OCCURRENCE                                   ...              
2018-12-04 05:10:00     065XX S UNIVERSITY AVE  0326  ...    5  Tuesday
2018-12-04 05:15:00  083XX S COTTAGE GROVE AVE  0810  ...    5  Tuesday
2018-12-04 05:30:00      079XX S GREENWOOD AVE  1310  ...    5  Tuesday
2018-12-04 05:50:00       010XX W GLENLAKE AVE  0890  ...    5  Tuesday
2018-12-04 06:00:00       077XX S EAST END AVE  2820  ...    6  Tuesday

[5 rows x 8 columns]

In [0]:
df.columns

Index(['BLOCK', ' IUCR', ' PRIMARY DESCRIPTION', 'ARREST', 'year', 'month',
       'hour', 'weekday'],
      dtype='object')

In [0]:
df.head(3)

BLOCK  IUCR  ... hour  weekday
DATE  OF OCCURRENCE                                   ...              
2018-12-04 05:10:00     065XX S UNIVERSITY AVE  0326  ...    5  Tuesday
2018-12-04 05:15:00  083XX S COTTAGE GROVE AVE  0810  ...    5  Tuesday
2018-12-04 05:30:00      079XX S GREENWOOD AVE  1310  ...    5  Tuesday

[3 rows x 8 columns]

In [0]:
#counting crimes
#crimes=df.groupby(by=[' PRIMARY DESCRIPTION']).size().sort_values(ascending=False)
#https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html
#print(crimes)

In [0]:
df.columns

Index(['BLOCK', ' IUCR', ' PRIMARY DESCRIPTION', 'ARREST', 'year', 'month',
       'hour', 'weekday'],
      dtype='object')

Locations are too much. if i focus on data by block than it can work out well

del df["LOCATION"]

In [0]:
"""
location_count = df.groupby(' LOCATION DESCRIPTION').size().sort_values(ascending=False)
pd.DataFrame(location_count)
location_count.head()
Locations with highest occurence of crime
"""

"\nlocation_count = df.groupby(' LOCATION DESCRIPTION').size().sort_values(ascending=False)\npd.DataFrame(location_count)\nlocation_count.head()\nLocations with highest occurence of crime\n"

In [0]:
df.columns

Index(['BLOCK', ' IUCR', ' PRIMARY DESCRIPTION', 'ARREST', 'year', 'month',
       'hour', 'weekday'],
      dtype='object')

#**Checking TOP 10 CRIMES for extractinng and using specific categories from dataframe**

In [0]:
crime_count = df.groupby(' IUCR').size().sort_values(ascending=False)
list(crime_count)
crime_count.head(10)
#Crimes with highest occurence

 IUCR
0486    23573
0820    22559
0460    16337
0810    14387
0560    13840
1310    12863
1320    12098
0860    10697
0890    10285
0910     7894
dtype: int64

#**SELECTING only some categories from IUCR column**

In [0]:
#https://www.interviewqs.com/ddi_code_snippets/rows_cols_python
c1= "0486"
c2= "0820"
c3= "0460"
c4= "0810"
c5= "0560"
c6= "1310"
c7= "1320"
c8= "0860"
c9= "0890"
c10="0910"
array = [c1,c2,c3,c4,c5,c6,c7,c8,c9,c10]
df2= df.loc[df[' IUCR'].isin(array)]

In [0]:
print("DF ", df.size)
print("DF2", df2.size)
print("difference of: ", df.size-df2.size)

DF  2040304
DF2 1156264
difference of:  884040


In [0]:
df2.head(3)

BLOCK  IUCR  ... hour  weekday
DATE  OF OCCURRENCE                                   ...              
2018-12-04 05:15:00  083XX S COTTAGE GROVE AVE  0810  ...    5  Tuesday
2018-12-04 05:30:00      079XX S GREENWOOD AVE  1310  ...    5  Tuesday
2018-12-04 05:50:00       010XX W GLENLAKE AVE  0890  ...    5  Tuesday

[3 rows x 8 columns]

#**Selecting X and Y from our dataset**

In [0]:
df2.columns

Index(['BLOCK', ' IUCR', ' PRIMARY DESCRIPTION', 'ARREST', 'year', 'month',
       'hour', 'weekday'],
      dtype='object')

In [0]:
#X= df.loc[:, ['BLOCK',' IUCR', ' PRIMARY DESCRIPTION',' LOCATION DESCRIPTION','year','month','hour','Weekday']].values
#https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html
X= df2.iloc[:, [1,2,3,4,5,6,7]].values
Y= df2.iloc[:, df.columns.get_loc('BLOCK')].values


In [0]:
df2.columns

Index(['BLOCK', ' IUCR', ' PRIMARY DESCRIPTION', 'ARREST', 'year', 'month',
       'hour', 'weekday'],
      dtype='object')

#**How many columns will be formed after Label Encoding**(Later on)

In [0]:
#checking 
iucr=     len(df2[" IUCR"].unique())
prim_des= len(df2[" PRIMARY DESCRIPTION"].unique())
arest=     len(df2["ARREST"].unique())
y=     len(df2["year"].unique())
m=    len(df2["month"].unique())
h=     len(df2["hour"].unique())
w=  len(df2["weekday"].unique())
print("IUCR: ", iucr)
print("PRIMARY DESCRIPTION: ", prim_des)
print("Arest: ", arest)
print("year: ", y)
print("hour: ", h)
print("month: ", m)
print("weekday: ", w)
print("After Label Encoder, Total columns Will be:", iucr+prim_des+arest+y+h+m+w)

IUCR:  10
PRIMARY DESCRIPTION:  5
Arest:  2
year:  2
hour:  24
month:  12
weekday:  7
After Label Encoder, Total columns Will be: 62


**.value** Returns a Numpy representation of the DataFrame.
Only the values in the DataFrame will be returned, the axes labels will be removed.

Checking which are Categorical columns

https://www.datacamp.com/community/tutorials/categorical-data#exploration

The columns with object dtype are the possible categorical features in your dataset.

#**LabelEncoding and than OneHotEncoding**

In [0]:
labelEncoder_X= LabelEncoder()
X[:,0]= labelEncoder_X.fit_transform(X[:,0])
X[:,1]= labelEncoder_X.fit_transform(X[:,1])
X[:,2]= labelEncoder_X.fit_transform(X[:,2])
X[:,3]= labelEncoder_X.fit_transform(X[:,3])
X[:,4]= labelEncoder_X.fit_transform(X[:,4])
X[:,5]= labelEncoder_X.fit_transform(X[:,5])
X[:,6]= labelEncoder_X.fit_transform(X[:,6])

#OneHotencoding.  Seperating each labeled categorie as a seperate new column for all the categorical data type column

In [0]:
onehotencoder= OneHotEncoder(categorical_features=[0,1,2,3,4,5,6]) 
X= onehotencoder.fit_transform(X).toarray()

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


#**Train Test Split**
To avoid over-fitting, we will divide our dataset into training and test splits, which gives us a better idea as to how our algorithm performed during the testing phase. This way our algorithm is tested on un-seen data, as it would be in a production application.

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20)

#**Feature Scaling**
Before making any actual predictions, it is always a good practice to scale the features so that all of them can be uniformly evaluated.

In [0]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

#**Training and Predictions**
It is extremely straight forward to train the KNN algorithm and make predictions with it, especially when using Scikit-Learn.

In [0]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

The first step is to import the KNeighborsClassifier class from the sklearn.neighbors library. In the second line, this class is initialized with one parameter, i.e. n_neigbours. This is basically the value for the K. There is no ideal value for K and it is selected after testing and evaluation, however to start out, 5 seems to be the most commonly used value for KNN algorithm.

In [0]:
y_pred = classifier.predict(X_test)

#**Evaluating the Algorithm**
For evaluating an algorithm, confusion matrix, precision, recall and f1 score are the most commonly used metrics. The confusion_matrix and classification_report methods of the sklearn.metrics can be used to calculate these metrics. 

In [0]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred)) b
print(classification_report(y_test, y_pred))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


                                     precision    recall  f1-score   support

                   0000X E 100TH PL       0.00      0.00      0.00         3
                   0000X E 100TH ST       0.00      0.00      0.00         1
                   0000X E 101ST PL       0.00      0.00      0.00         1
                   0000X E 101ST ST       0.00      0.00      0.00         2
                   0000X E 102ND PL       0.00      0.00      0.00         5
                   0000X E 102ND ST       0.00      0.00      0.00         2
                   0000X E 103RD PL       0.00      0.00      0.00         2
                   0000X E 103RD ST       0.00      0.00      0.00         4
                   0000X E 104TH ST       0.00      0.00      0.00         2
                   0000X E 105TH ST       0.00      0.00      0.00         2
                   0000X E 107TH ST       0.00      0.00      0.00         2
                   0000X E 108TH ST       0.00      0.00      0.00         

#**Comparing Error Rate with the K Value**
In the training and prediction section we said that there is no way to know beforehand which value of K that yields the best results in the first go. We randomly chose 5 as the K value and it just happen to result in 100% accuracy.

One way to help you find the best value of K is to plot the graph of K value and the corresponding error rate for the dataset.

In this section, we will plot the mean error for the predicted values of test set for all the K values between 1 and 40.

To do so, let's first calculate the mean of error for all the predicted values where K ranges from 1 and 40.

In [0]:
error = []

# Calculating error for K values between 1 and 40
for i in range(1, 40):
    knn = KNeighborsClassifier(n_neighbors=i)
    knn.fit(X_train, y_train)
    pred_i = knn.predict(X_test)
    error.append(np.mean(pred_i != y_test))

NameError: ignored

In [0]:
plt.figure(figsize=(12, 6))
plt.plot(range(1, 40), error, color='red', linestyle='dashed', marker='o',
         markerfacecolor='blue', markersize=10)
plt.title('Error Rate K Value')
plt.xlabel('K Value')
plt.ylabel('Mean Error')

#**Conclusion**
KNN is a simple yet powerful classification algorithm. It requires no training for making predictions, which is typically one of the most difficult parts of a machine learning algorithm. The KNN algorithm have been widely used to find document similarity and pattern recognition. It has also been employed for developing recommender systems and for dimensionality reduction and pre-processing steps for computer vision, particularly face recognition tasks.

From here, I would advise you to implement the KNN algorithm for a different classification dataset. Vary the test and training size along with the K value to see how your results differ and how can you improve the accuracy of your algorithm. A good collection of classification datasets is available here for you to play with.